GAFpath: /home/rain/PythonProject/GFD/data/gearbox_data/GAF
accelerator: null
accumulate_grad_batches: null
amp_backend: native
amp_level: null
aug_prob: 0.5
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 32
batchnorm_num_features:
- 16
- 32
- 64
- 64
- 64
benchmark: null
check_val_every_n_epoch: 1
checkpoint_callback: null
class_num: 10
computational_graph: false
conv_paddings:
- 0
- 0
- same
- same
- valid
criterion: ce
data_dir: /home/rain/PythonProject/GFD/data/gearset
dataset: gearbox_data
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
fc_hidden_dim: 100
flush_logs_every_n_steps: null
fold_num: 0
gpus:
- 2
gradient_clip_algorithm: null
gradient_clip_val: null
in_channel: 8
ipus: null
kernel_sizes:
- 64
- 16
- 3
- 3
- 3
kfold: 5
layer_num: 3
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
load_best: false
load_dir: null
load_ver: null
load_version_num: null
log_dir: lightning_logs
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 0.001
lr_decay_min_lr: 1.0e-05
lr_decay_rate: 0.3
lr_decay_steps: 50
lr_scheduler: step
max_epochs: 100
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model_name: onedcnn_net
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
no_augment: false
num_layers: 4
num_nodes: 1
num_processes: null
num_sanity_val_steps: 1
num_workers: 16
out_channels:
- 16
- 32
- 64
- 64
- 64
overfit_batches: 0.0
plugins: null
pool_kernel_sizes:
- 2
- 2
- 2
- 2
- 2
power: 5
precision: 32
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
ref_dir: /home/rain/PythonProject/GFD/data/ref
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
sample_length: 4096
sample_number: 100
seed: 1234
sensor_number: 8
standard_scalar: true
stochastic_weight_avg: false
strategy: null
strides:
- 32
- 8
- 1
- 1
- 1
sync_batchnorm: false
terminate_on_nan: null
tpu_cores: null
track_grad_norm: -1
train_mode: true
train_size: 0.8
transforms:
  train: !!python/object:torchvision.transforms.transforms.Compose
    transforms:
    - !!python/object:torchvision.transforms.transforms.Resize
      _backward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _buffers: !!python/object/apply:collections.OrderedDict
      - []
      _forward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _is_full_backward_hook: null
      _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _modules: !!python/object/apply:collections.OrderedDict
      - []
      _non_persistent_buffers_set: !!set {}
      _parameters: !!python/object/apply:collections.OrderedDict
      - []
      _state_dict_hooks: !!python/object/apply:collections.OrderedDict
      - []
      antialias: null
      interpolation: &id001 !!python/object/apply:torchvision.transforms.functional.InterpolationMode
      - bilinear
      max_size: null
      size: &id002 !!python/tuple
      - 224
      - 224
      training: true
    - !!python/object:torchvision.transforms.transforms.ToTensor {}
    - !!python/object:torchvision.transforms.transforms.Normalize
      _backward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _buffers: !!python/object/apply:collections.OrderedDict
      - []
      _forward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _is_full_backward_hook: null
      _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _modules: !!python/object/apply:collections.OrderedDict
      - []
      _non_persistent_buffers_set: !!set {}
      _parameters: !!python/object/apply:collections.OrderedDict
      - []
      _state_dict_hooks: !!python/object/apply:collections.OrderedDict
      - []
      inplace: false
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
      training: true
  val: !!python/object:torchvision.transforms.transforms.Compose
    transforms:
    - !!python/object:torchvision.transforms.transforms.Resize
      _backward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _buffers: !!python/object/apply:collections.OrderedDict
      - []
      _forward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _is_full_backward_hook: null
      _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _modules: !!python/object/apply:collections.OrderedDict
      - []
      _non_persistent_buffers_set: !!set {}
      _parameters: !!python/object/apply:collections.OrderedDict
      - []
      _state_dict_hooks: !!python/object/apply:collections.OrderedDict
      - []
      antialias: null
      interpolation: *id001
      max_size: null
      size: *id002
      training: true
    - !!python/object:torchvision.transforms.transforms.ToTensor {}
    - !!python/object:torchvision.transforms.transforms.Normalize
      _backward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _buffers: !!python/object/apply:collections.OrderedDict
      - []
      _forward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _is_full_backward_hook: null
      _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _modules: !!python/object/apply:collections.OrderedDict
      - []
      _non_persistent_buffers_set: !!set {}
      _parameters: !!python/object/apply:collections.OrderedDict
      - []
      _state_dict_hooks: !!python/object/apply:collections.OrderedDict
      - []
      inplace: false
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
      training: true
val_check_interval: null
weight_decay: 1.0e-05
weights_save_path: null
weights_summary: full
